### ISSUE TITLE
同学你好，想请教一下你写的NEMU的事情

### ISSUE THREAD

**Issue by lambda7xx** [110101001/NEMU#1]
由于在下也打算做这个PA,但是处理点问题，我把你的NEMUclone到我本地上，你的PA2好像很多指令测试通不过，能否请教一下

**Comment by 110101001** [comment]
不好意思现在才看到。
有个config.h，在PA的每个阶段这个文件的配置都是不一样的，我的这个是第四阶段的配置。时间有点久了我也记不清要改哪些地方。你可能得参考一下网址里的的PA_GUIDE。

**Comment by lambda7xx** [comment]
多谢

吴沛聪 <notifications@github.com> 于2018年9月24日周一 下午6:37写道：
